name: fingu-telegram
services:
  fingu-telegram-server:
    image: fingu/telegram
    build:
      context: .
      dockerfile: Dockerfile.alpha
    ports:
      - 8000:8000
    volumes:
      - .:/app
    restart: always
